import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/reuse/sidebar/sidebar";
import {
  footerActions,
  navSections,
  userProfile,
} from "@/config/sidebar-config";
import { DashboardHeader } from "@/components/reuse/header/header";
import { headerConfig } from "@/config/header-config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}
      >
        <AppSidebar
          isCollapsed={false}
          navSections={navSections}
          footerActions={footerActions}
          userProfile={userProfile}
        />
        <main className="flex-1">
          <DashboardHeader
            {...headerConfig}
            notificationCount={3}
            userName="John Doe"
            userAvatar="/placeholder.svg?height=32&width=32"
          />
          <div className="p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
